node {
  stage('Checkout') {
    echo "Checking out source code"
    checkout scm
  }

  stage('Install dependencies') {
    echo "Installing dependencies"
    sh 'npm install'
  }

  stage('Build') {
    echo "Build is in progress..."
    sh 'npm run build'
  }

  echo "Pipeline succeeded! App is ready for deployment"
}
