pipeline {
  agent any 
  stages {
    stage('checkout'){
      checkout scm
    }
    stage('install dependencies') {
      steps {
        sh 'npm install'
      }
      stage('build') {
        echo "Build is in progress" 
        sh 'npm run build' 
      }
    }
  }

  post {
    success {
      echo "Pipeline succeeded! App is ready for deployment"
    }
    failure {
      echo "Pipeline failed, Please check logs for errors."
    }
  }
}
