pipeline {
  agent any

  stages {
    stage('checkout') {
      steps {
        checkout scm
      }
    }
    stage('install dependencies') {
      steps {
        dir('multi-app') {
          sh 'npm install'
        }
      }
    }
    stage('lint html') {
      steps {
        dir('multi-app') {
          sh 'npx htmllint *.html'
        }
      }
    }
    stage('lint css') {
      steps {
        dir('multi-app') {
          sh 'npx stylelint "*.css"'
        }
      }
    }
    stage('lint js') {
      steps {
        dir('multi-app') {
          sh 'npx eslint *.js'
        }
      }
    }
    stage('deploy') {
      steps {
        echo "Deploying application locally"
        sh 'mkdir -p /home/pipe/projects/exercise1'
        sh 'cp -r ./multi-app/* /home/pipe/projects/exercise1'
      }
    }
  }

  post {
    success {
      echo "Pipeline succeeded! App is ready for deployment"
    }
    failure {
      echo "Pipeline failed, Please check logs for errors."
    }
  }
}
