pipeline {
  agent any

  stages {
    stage('checkout') {
      steps {
        checkout scm
      }
    }

    stage('deploy') {
      steps {
        echo "Deploying application locally"
        sh 'mkdir -p /home/pipe/projects/exercise1'
        sh 'cp -r * /home/pipe/projects/exercise1/'
      }
    }
  }

  post {
    success {
      echo "Pipeline succeeded! App is ready for deployment"
    }
    failure {
      echo "Pipeline failed, Please check logs for errors."
    }
  }
}
